# Generated by Django 4.0.3 on 2022-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.CharField(default='PROCEED', max_length=255),
        ),
    ]
