# Generated by Django 4.0.3 on 2022-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_grade_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
