# Generated by Django 4.0.3 on 2022-04-15 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_alter_course_program_alter_program_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=255)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('marital_status', models.CharField(choices=[('maried', 'Maried'), ('single', 'Single')], max_length=255)),
                ('national_id_or_passport', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('home_address', models.CharField(max_length=255)),
                ('nok_full_name', models.CharField(max_length=255)),
                ('nok_phone', models.CharField(max_length=255)),
                ('nok_country', models.CharField(max_length=255)),
                ('nok_province', models.CharField(max_length=255)),
                ('nok_physical_adress', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
